# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"terminal - floating" = "ï„ "
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"file manager" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ğŸ—‹"
"libreoffice" = "ï£…"
"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ï‹"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ğŸ—"
"emacs" = "ğ“”"
"spotify" = "ï†¼"
"steam" = "ï†¶"
"gimp" = "ï‡¼"
"discord" = "ï’"
"files" = "k"
"openscad" = "ï†²"
"cura" = "â™"
"swappy" = "ğŸ–µ"

[other]
fallback_icon = "â€½"
deduplicate_icons = true
separator = ": "
